### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by stereobooster** [tenderlove/csspool#19]
If I want to implement following features for parser

``` css
input[type="search"]::-webkit-search-decoration { color: #000; }
a{*margin:0;}
@media only screen and (min-width: 35em) { a{ color: #000; } }
```

where should I place tests?
