### ISSUE TITLE
support  `:not()` selector

### ISSUE THREAD

**Issue by stereobooster** [tenderlove/csspool#26]
example

``` css
/*
 * Prevents modern browsers from displaying 'audio' without controls
 * Remove excess height in iOS5 devices
 */
/* line 44, ../_scss/foundations/_normalise.scss */
audio:not([controls]) {
  display: none;
  height: 0;
}
```
