### ISSUE TITLE
Parser hang with unclosed URL and bad characters?

### ISSUE THREAD

**Issue by JasonBarnabe** [tenderlove/csspool#38]
CSSPool hangs parsing http://userstyles.org/hang.css. I believe there's something about the charset used because it doesn't occur when defined as a string

``` css
body{
background: url("http://example.com);
}


/* Â¯Â¯Â¯Â¯Â¯Â¯Â¯Â¯Â¯Â¯Â¯Â¯Â¯ */
```

``` ruby
CSSPool.CSS open('./hang.css')
```
