### ISSUE TITLE
Get original source of a node

### ISSUE THREAD

**Issue by JasonBarnabe** [tenderlove/csspool#52]
After parsing a stylesheet, I would like to be able to get the source code for a node. For example, given this CSS:

``` css
@document domain(github.com) {
/* this is to make things black */
body { color: black !important;}
}
```

I would like to be able to get the original code for the @document's children, including the comments and original whitespace (i.e. not the parsed and reconstituted code).
