### ISSUE TITLE
font-face failure

### ISSUE THREAD

**Issue by JasonBarnabe** [tenderlove/csspool#61]
``` css
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document domain(example.com) {
@font-face { /* empty for brevity */ }
#element { display: none; }
}
```
